config/routes.rb
Rails.application.routes.draw do
  root 'shirts#index'
  get 'shirts/index'
  get 'shirts/', to:'shirts#index'
  get '/search' => 'shirts#search'
  get '/new' => 'shirts#new'
  post '/new' => 'shirts#create', as: 'tshirts'

  

end

app/models/tshirt.rb
class Tshirt < ActiveRecord::Base
	validates :name, presence: true, uniqueness: true
	validates :description, presence: true
	
	def self.search(search)
		self.where( "name LIKE ?", "%#{search}%" ).first
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/shirts_controller.rb
class ShirtsController < ApplicationController
  def index
  	@shirts = Tshirt.order('id DESC').all
  end

  def search
  	@search = params[:q]
  	@shirt = Tshirt.search(@search)
  	@no_results = !@shirt
  end

  def new
  	@shirt = Tshirt.new
  end

  def create
  	@shirt = Tshirt.new(parameters)
    if @shirt.valid?
    	@shirt.save
      flash[:info] = 'Yay! T-Shirt Created Succesfully'
      redirect_to root_path and return
    end

    flash[:error] = "You are an idiot!"
  end

	private
	def parameters
		params.require(:tshirt).permit(:name, :description)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/shirts_helper.rb
module ShirtsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tshirts</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

Error: <% flash[:error] if flash[:error] %><br>
Info: <% flash[:info] if flash[:info] %>
	<div id="Body">
		<%= yield %>
	</div>
</body>
</html>

app/views/shirts/_form.html.erb
<%= form_for @shirt do |f| %>
	Name: <%= f.text_field :name %><br>
	Description: <%= f.text_field :description %><br>
	<%= f.submit('Create')%>
<% end %>

app/views/shirts/_shirt.html.erb
<h2><%= a_shirt.name %></h2>
<p><strong>Description:</strong><br><blockquote><%= a_shirt.description %></blockquote><p>
<p><%= image_tag a_shirt.image, size: '250' %></p>
<hr>

app/views/shirts/create.html.erb
<% if @shirt.errors.any? %>
<ol>
<% @shirt.errors.full_messages.each do |message| %>
<li><%= message %></li>
<% end %>
</ol>
<% end %>

<%= render partial: 'form', locals: { shirt: @shirt } %>

app/views/shirts/index.html.erb
<h1>
	Here are my t-shirts!
</h1>

<form action= "/search" action="post">
	<input name="q" type="text"/>
	<button>Search</button>
</form>

<p>
	<%= link_to 'create new', tshirts_path %>
</p>

<% @shirts.each do |shirt| %>
	<%= render partial: 'shirt', locals: { a_shirt: shirt } %>
<% end %>

app/views/shirts/new.html.erb
<h1>Create a new Shirt</h1>

<!-- <hr>
tshirts_path: <%= tshirts_path %>
<br>
roo_path: <%= root_path %>
<hr> -->

<%= render partial: 'form', locals: { shirt: @shirt } %>

app/views/shirts/search.html.erb
<h1>You Searched for: <%= @search %></h1>

<% if @no_results %>
<h1>NOT FOUND</h1>
<% else %>
<p>Here's your shirt:</p>
<p>
<%= render partial: 'shirt', locals: { a_shirt: @shirt } %>
</p>

<% end %>